/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.vutbr.fit.pdb.interf;

import cz.vutbr.fit.pdb.Base.ReloadDatabaseModel;
import cz.vutbr.fit.pdb.hlavni.DataBase;
import cz.vutbr.fit.pdb.hlavni.InvalidCredentialsException;
import cz.vutbr.fit.pdb.system.Identifikace1;
import cz.vutbr.fit.pdb.system.Loader;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import cz.vutbr.fit.pdb.interf.ParkMainPanel1;

/**
 *Forma pro pripojeni do DB
 * @author Iuliia Ogloblina
 */
public class Registrace extends javax.swing.JPanel {



private ParkMainPanel1 mainPanel;

public void setParkMainPanel(ParkMainPanel1 mainPanel) {
        this.mainPanel = mainPanel;
    }
    /**
     * Creates new form Registrace
     * 
     */

    /**
     * Creates new form Registrace
     * @return
     */
    public String getIdentityName() {
        Identifikace1 identity = DataBase.getIdentifikace().getIdentity();
        if (identity.isLoggendIn()) {
            return identity.getUsername();
        } else {
            if (ReloadDatabaseModel.isConnectionValid()) {
                return "Nepřihlášen";
            }
        }
    return null;
    }

	
    public Registrace() {
        initComponents();
       jLabel2.setVisible(false);
        if (!Loader.existsLocalConfig()) {
           reset_database.setEnabled(false);
        }
    }
    
 public void updateIdentityNameLabel() {
        jLabel5.setText(getIdentityName());
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
      class BackgroundWorker extends SwingWorker<String, Integer> {

        @Override
        protected void done() {
            try {
                //jLabel1.setVisible(false);
               LogIn.setEnabled(true);
               reset_database.setVisible(false);
                mainPanel.setPanelVisibility(true);
                mainPanel.checkPanelAvailability();
                JOptionPane.showMessageDialog(getParent(), get());
            } catch (InterruptedException | ExecutionException | HeadlessException ex) {
                Logger.getLogger(Registrace.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        @Override
        protected String doInBackground() throws Exception {
            reset_database.setVisible(true);
            // Do a time-consuming task.
            try {
                ReloadDatabaseModel.resetDatabase();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(getParent(), ex.getMessage(), "Reset databáze se nezdařil", JOptionPane.ERROR_MESSAGE);
            }
            return "Reset databáze je dokončen!";
        }
    
      }
       
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        LogIn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        reset_database = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        Username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                username(evt);
            }
        });

        jLabel1.setText("Uživatelské jméno");

        jLabel3.setText("Heslo");

        Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                password(evt);
            }
        });

        LogIn.setText("LogIn");
        LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInActionPerformed(evt);
            }
        });

        jLabel2.setText("jLabel2");

        reset_database.setText("Reset database");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Vítejte");

        jLabel5.setText("login");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Username)
                            .addComponent(Password, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(reset_database, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogIn)
                    .addComponent(reset_database))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInActionPerformed
String username = Username.getText();
        String password = new String(Password.getPassword());

        try {
            DataBase.getIdentifikace().login(username, password);
            reset_database.setEnabled(true);
        } catch (InvalidCredentialsException ex) {
            JOptionPane.showMessageDialog(getParent(), ex.getMessage(), "Přihlášení se nezdařilo", JOptionPane.ERROR_MESSAGE);
        }

        updateIdentityNameLabel();
        Password.setText("");
        Username.setText("");
        mainPanel.checkPanelAvailability();
    }//GEN-LAST:event_LogInActionPerformed

    private void username(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username
        // TODO add your handling code here:
         Username.setText("");
    }//GEN-LAST:event_username

    private void password(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password
        // TODO add your handling code here:
        Password.setText("");
    }//GEN-LAST:event_password


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogIn;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton reset_database;
    // End of variables declaration//GEN-END:variables
}
