/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.vutbr.fit.pdb.interf;

import cz.vutbr.fit.pdb.Base.Obrazky;
import java.awt.Color;
import java.sql.SQLException;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Olga
 */
public class ViewObjektu extends javax.swing.JPanel {

    /**
     * Creates new form ViewObjektu
     * Vysledky vyhledovani
     */
    public ViewObjektu(Integer id) {
        initComponents();
        setImage(id);
        Vyhled();
    }

    /**
     * 
     * @param id 
     */
    
       private void setImage(Integer id) {
           this.Image =id;
       }
       
       
        private void Vyhled() {
            View.setLayout(new BoxLayout(View, BoxLayout.Y_AXIS));
        Obraz = new Obrazky();
        Map<Integer, Objekty> result = null;
        try {
            result = Obraz.getTheMostSimilar(Image, 0.5, 0.5, 0.5, 0.1);
        } catch (SQLException e) {
            Logger.getLogger(ViewObjektu.class.getName()).log(Level.SEVERE, null, e);
        }
        if (result != null && result.size() > 0) {
            for (Map.Entry<Integer, Objekty> entry : result.entrySet()) {
                Objekty value = entry.getValue();
                value.setIcon(value.getObjekty());
                value.setText(value.getScoreAsString());
                value.setToolTipText("Čím menší skóre, tím podobnější obrázek");
                View.add(value);
            }
        } else if(result.size() <= 0){
            JLabel warn = new JLabel("Žádné podobné obrázky! V databázi se nachází pravděpodobně jediný obrázek");
            String path = "/imagess/Info.png";
            ImageIcon i = new ImageIcon(getClass().getResource(path));
            warn.setIcon(i);
            warn.setBackground(Color.LIGHT_GRAY);
            View.add(warn);
        }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        View = new javax.swing.JPanel();

        javax.swing.GroupLayout ViewLayout = new javax.swing.GroupLayout(View);
        View.setLayout(ViewLayout);
        ViewLayout.setHorizontalGroup(
            ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        ViewLayout.setVerticalGroup(
            ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(View);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel View;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

 private Integer Image;
 private Obrazky Obraz;

   
}
